In [36]:
from tensorflow.keras.preprocessing.text import one_hot

In [30]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [21]:
#DEFINE THE VOCAB SIZE
voc_size = 10000

In [22]:
#ONE HOT REPRESENTATION
one_hot_representation = [one_hot(words,voc_size)for words in sent]
one_hot_representation

[[1468, 6649, 557, 5337],
 [1468, 6649, 557, 3456],
 [1468, 9339, 557, 6299],
 [830, 9648, 8239, 6183, 2977],
 [830, 9648, 8239, 6183, 1861],
 [1503, 1468, 145, 557, 3227],
 [6500, 3088, 3180, 6183]]

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [33]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_representation,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1468 6649  557 5337]
 [   0    0    0    0 1468 6649  557 3456]
 [   0    0    0    0 1468 9339  557 6299]
 [   0    0    0  830 9648 8239 6183 2977]
 [   0    0    0  830 9648 8239 6183 1861]
 [   0    0    0 1503 1468  145  557 3227]
 [   0    0    0    0 6500 3088 3180 6183]]


In [26]:
dim = 10

In [31]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse")

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step


array([[[-0.04867163,  0.01350002, -0.00186199, -0.02929556,
         -0.00386003,  0.01207682, -0.00511199,  0.04180111,
         -0.04519505,  0.01436892],
        [-0.04867163,  0.01350002, -0.00186199, -0.02929556,
         -0.00386003,  0.01207682, -0.00511199,  0.04180111,
         -0.04519505,  0.01436892],
        [-0.04867163,  0.01350002, -0.00186199, -0.02929556,
         -0.00386003,  0.01207682, -0.00511199,  0.04180111,
         -0.04519505,  0.01436892],
        [-0.04867163,  0.01350002, -0.00186199, -0.02929556,
         -0.00386003,  0.01207682, -0.00511199,  0.04180111,
         -0.04519505,  0.01436892],
        [-0.02321991,  0.00656837, -0.00876186,  0.04505875,
         -0.01695204,  0.0077045 , -0.02776427, -0.00944319,
         -0.01764705,  0.04298678],
        [ 0.02657816, -0.0236356 ,  0.00647205,  0.02039177,
         -0.03442677, -0.00501138,  0.00531245,  0.00275182,
          0.04860163,  0.04457674],
        [ 0.01597545, -0.02103153,  0.03633634, -0.0

In [35]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)